name = "waifu-dev-web"
compatibility_date = "2024-07-29"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

# Disable default *.pages.dev domains
# workers_dev = false

# [[routes]]
# pattern = "www.waifu.dev"
# custom_domain = true

[[services]]
binding = "API"
service = "waifu-dev-api"
