name: Deploy web to cloudflare

on:
  push:
    branches:
      - main

jobs:
  deploy_web:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    #   deployments: write
    name: Deploy web
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1

      - name: Install dependencies
        run: bun install

      - name: Opt out of telemetry
        run: bunx next telemetry disable

      - name: Print build info
        run: bunx @cloudflare/next-on-pages@latest --info

      - name: Build
        run: bunx @cloudflare/next-on-pages@latest
        env:
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          wranglerVersion: "3.70.0"
          packageManager: bun
          command: pages deploy .vercel/output/static --project-name waifu-dev-web --commit-dirty true